# -*- coding: utf-8 -*-
"""googletrendsABA_MSciProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iszGNU7jLrW9E3p9zoSXxfUkCHsm-O7u
"""

!pip install pytrends

!pip install --upgrade --user git+https://github.com/GeneralMills/pytrends

import pandas as pd
from pytrends.request import TrendReq
import time
import datetime
from datetime import datetime, date, time

"""### Use pytrends to scrape google trends data - topic interests over the past 5 years

Pytrends documentation: https://pypi.org/project/pytrends/#interest-over-time

According to the Google Trends website <b>Interest over time (IOT)</b> = numbers represent search interest relative to the highest point on the chart for the given region and time. A value of 100 is the peak popularity of the term. A vlaue of 50 means that the term is half as popular. A score of 0 means there was not engouh data for this term. This 0 to 100 scale will be refered further as the trends index.

Each point represents the interest over time for a given week.

The region selected for the analysis is 'worldwide'.

Topic queried: 'Applied behaviour analysis'.
Date of query : 28/07/2023

"""

# pytrend = TrendReq()
# time zone codes can be found: https://forbrains.co.uk/international_tools/earth_timezones
# setting the timezone to BST does not change the results
pytrend = TrendReq(hl='en-US', tz=60, retries=2, requests_args={'verify':False})

# # this will return different results from the the website because:
# # https://stackoverflow.com/questions/59901790/why-is-data-downloaded-via-pytrends-drastically-different-from-using-the-google
# pytrend.build_payload(kw_list=['Applied behavior analysis'], timeframe='today 5-y', geo='')

# google trends uses FREEBASE ID for topic related searches. Applied Behavior Analysis FREEBAE ID = /m/05wf1w (https://www.wikidata.org/wiki/Q621607)
# geo='' means the region is set to 'worldwide' (see pytrends documentation cited above)
pytrend.build_payload(kw_list=['/m/05wf1w'], timeframe='today 5-y' , geo ='')

pytrends_iot_df = pytrend.interest_over_time()
pytrends_iot_df.info()

pytrends_iot_df = pytrends_iot_df.rename(columns={"/m/05wf1w": "Applied behavior analysis"})

pytrends_iot_df.head()

# visualise IOT
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(color_codes='true')
dx = pytrends_iot_df.plot.line(figsize= (30,6), title=("Interest Over Time"))
dx.set_xlabel('Date')
dx.set_ylabel('Trends Index')

"""### Use Google Trends website data - topic interest over the past 5 years
The following represents the same analysis as above except the data has been manually downloaded from Google's website (https://trends.google.com/trends/explore?date=today%205-y&q=%2Fm%2F05wf1w&hl=en)

Date of query : 28/07/2023




"""

# read the data
site_df = pd.read_csv('aba_gt_global/GTweb_iot_worldwide.csv')
site_df.head()

# rename the columns with the correct lables
site_df.columns = site_df.iloc[1]
site_df.head()

# remove the first 2 rows on the data set - first row was an empty row and the second row contained the columns lables
site_df = site_df.tail(-2)
site_df.head()

# trends index for Applied behavior analysis is stored as a string/object value
# week date is stored as a string/object value
site_df.info()

# change type of Trends index for Applied behavior analysis from object to int
site_df = site_df.astype({'Applied behavior analysis: (Worldwide)':'int'})
# change the type of week date data from object to datetime
site_df['Week'] = pd.to_datetime(site_df['Week'])

site_df.info()

# visualize IOT
site_df = site_df.set_index(site_df['Week'])
dx = site_df['Applied behavior analysis: (Worldwide)'].plot.line(figsize=(30,6), title=("Interest Over Time"))
dx.set_xlabel('Date')
dx.set_ylabel('Trends Index')

"""The above code shows discrepancies between the data obtained via pytrends vs. via google's official website. I have failed to find the explanation for why this is the case - apparently the data proivded when making calls as legit-user vs scraper is different (https://stackoverflow.com/questions/73988220/why-google-retrieves-different-info-to-scrapers). Google Trends does not have an official API and thus reliability on 3rd party scraping tools can result in questionalble data. I have thus decided to manually download the data from google'e website direclty - the amount of data sets is small and thus this process is faster than to try to figure out a reliable and efficient method of scraping google trends data (this is out of the scope of the current project).

## Google trends data for queries related to the topic: Applied Behaviour Analysis

Date of query : 28/07/2023
Time frame: past 5 years

Data sets obtained:
1. IOT worldwide - analysis provided above
2. Interest by region (Country) worldwide
3. Related topics - worldwide
4. Related queries - worldwide

5. IOT - UK
6. Interest by region (Country) UK
7. Related topics - UK
8. Related queries - UK

### Interest by region (Country) worldwide
"""

# read file -> we observe there is missing data
ibr_world_df = pd.read_csv('aba_gt_global/geoMap_global.csv')
ibr_world_df.head()

# rename the columns with the correct lables
ibr_world_df.columns = ibr_world_df.iloc[0]
ibr_world_df.head()

# remove first row
ibr_world_df = ibr_world_df.tail(-1)
ibr_world_df.head()

# set all NaN values to 0 (= no google trends data for that entry)
ibr_world_df['Applied behavior analysis: (7/28/18 - 7/28/23)'] = ibr_world_df['Applied behavior analysis: (7/28/18 - 7/28/23)'].fillna(0)
ibr_world_df.head()

ibr_world_df.info()

# change type of Trends index for Applied behavior analysis from object to int
ibr_world_df = ibr_world_df.astype({'Applied behavior analysis: (7/28/18 - 7/28/23)':'int'})
ibr_world_df.info()

# sort countries/regions by trending index
ibr_world_df = ibr_world_df.sort_values(by=['Applied behavior analysis: (7/28/18 - 7/28/23)'], ascending=False)
ibr_world_df.head(10)

"""Applied behavior analysis seems to be very popular in Uganda and many African countries.However, the data reflects queries related to the topic, not the term, of Applied behavior analysis.
This means data reflects all possible related words, inculding misspellings and acronims. A brief investigation revealed that 2 popular companies in Uganda - one sports betting agency and one ofering financial services - have ABA in their name. This could be acounting for the incresed number of searches using the keyword 'aba' in Uganda.

Uganda 'ABA' companies: https://www.google.com/search?q=aba+uganda&oq=aba+uganda&aqs=chrome.0.69i59j46i175i199i512j0i22i30l2j0i10i22i30j0i22i30l2j69i60.3892j0j4&sourceid=chrome&ie=UTF-8

When a search in Google Trends was made for the search term 'Applied behavior analysis' (this shows just the exact match queries), USA appears to be the region where Applied behavior analysis trends the highest.

Google Trends data for 'Applied behavior analysis' as a search word:
https://trends.google.com/trends/explore?date=today%205-y&q=Applied%20behavior%20analysis&hl=en


Applied behavior analysis' popularity worldwide is not the topic of the current project so this issue will not be investigated further. Google trends data is used in the current project in order to find related key words to 'Applied behavior analysis' - > these are available in the *related queries dataset*. The related words are used to form a word bank of keywords for searching the relevant social media posts from the  Reddit platform.

### Related topics - worldwide

Accodring to Google Trends website Related topics means:

Users searching for your term also searched for these topics. You can view by the following metrics:
* Top - The most popular topics. Scoring is on a relative scale where a value of 100 is the most commonly searched topic and a value of 50 is a topic searched half as often as the most popular term, and so on.

* Rising - Related topics with the biggest increase in search frequency since the last time period. Results marked "Breakout" had a tremendous increase, probably because these topics are new and had few (if any) prior searches.
"""

# upload data
# data is formated strangely -> see possible sollutions at https://stackoverflow.com/questions/18039057/python-pandas-error-tokenizing-data
rt_world_df = pd.read_csv('aba_gt_global/relatedEntities_topics_global.csv', skiprows=2)
rt_world_df

# select top 25 related topics (maximum Google Trends provided)
rt_world_df_top = rt_world_df.iloc[:25]
rt_world_df_top = rt_world_df_top.reset_index()
rt_world_df_top = rt_world_df_top.rename(columns={"index": "Top related topic", "TOP": "Trend index"})
rt_world_df_top.head()

# select rising related topics
rt_world_df_rising = rt_world_df.iloc[25:]
rt_world_df_rising = rt_world_df_rising.reset_index()
rt_world_df_rising = rt_world_df_rising.rename(columns={"index": "Rising related topic", "TOP": "Trend index"})
rt_world_df_rising = rt_world_df_rising.tail(-1)
rt_world_df_rising.head()

"""The data above shows Applied behaviour analysis is commonly related to Therapy and Autistic Spectrum Disorders (see TOP: rt_world_df_top).

It seems that recently there has been a high increase in queries on Autism and Applied behaviour analysis (see RISING: rt_world_df_rising)

### Related queries - worldwide

Accodring to Google Trends website Related queries means:

Users searching for your term also searched for these queries. You can sort by the following metrics:
* Top - The most popular search queries. Scoring is on a relative scale where a value of 100 is the most commonly searched query, 50 is a query searched half as often as the most popular query, and so on.

* Rising - Queries with the biggest increase in search frequency since the last time period. Results marked "Breakout" had a tremendous increase, probably because these queries are new and had few (if any) prior searches.
"""

# read data
rq_world_df = pd.read_csv('aba_gt_global/relatedQueries_search_global.csv', skiprows=2)
# select top 25 related queries/words ( this is the maximum Google Trends provided)
rq_world_df_top = rq_world_df.iloc[:25]
rq_world_df_top = rq_world_df_top.reset_index()
rq_world_df_top.head()

# rename the columns appropriately
rq_world_df_top = rq_world_df_top.rename(columns={"index": "Top related query word", "TOP": "Trend index"})
rq_world_df_top.head()

# select the rising related queries/words
rq_world_df_rising = rq_world_df.iloc[25:]
rq_world_df_rising = rq_world_df_rising.reset_index()
rq_world_df_rising.head()

# rename the columns appropriately
rq_world_df_rising = rq_world_df_rising.rename(columns={"index": "Rising related query word", "TOP": "search increase"})
# drop the first row (this is a column lables row; the columns have already been renamed above)
rq_world_df_rising = rq_world_df_rising.tail(-1)
rq_world_df_rising.head()

"""The 2 data frames created above will be used as a word bank for related query words related to the topic of 'Applied behavior anlysis'.

The 2 data bases representig global data:
- rq_world_df_rising
- rq_world_df_top

### IOT - UK
"""

iot_uk_df = pd.read_csv('aba_gt_uk/GTweb_iot_UK.csv')
iot_uk_df.head()

"""### Interest by region (Country) UK"""

ibr_uk_df = pd.read_csv('aba_gt_uk/geoMap_UK.csv')
ibr_uk_df.head()

"""### Related topics - UK"""

rt_uk_df = pd.read_csv('aba_gt_uk/relatedEntities_topics_UK.csv', skiprows=2)
rt_uk_df.head()

"""### Related queries - UK"""

rq_uk_df = pd.read_csv('aba_gt_uk/relatedQueries_search_UK.csv', skiprows=2)
rq_uk_df.head()